### ISSUE TITLE
Constantly failing condition check

### ISSUE THREAD

**Issue by anykeyh** [crystal-ameba/ameba#128]
There's a trick in crystal which can confuse ruby developers: `'` stands for character definition while `"` stands for string definition.

It can lead to confusing non-working code like theses examples below:

```crystal
x = "b"
puts "Hello world" if x == 'b' #Will be false
```

```crystal
x = "hello"
puts "Hello world" if x[1] == "b" #Will be false too
```

I don't know if ameba could detect this kind of error in the near future?

**Comment by veelenga** [comment]
Unfortunately, right now ameba doesn't have any info about types since it does only a static analysis. To be able to solve the case above, we would need to introduce a lexical analysis, which will give a possibility to infer the type of variable `x` and report accordingly. 

This is planned, but don't expect it in a nearest future.

**Comment by veelenga** [comment]
I am going to close this for now and think about it when we are able to do a lexical analysis.
