### ISSUE TITLE
Incorrect Lint/EmptyExpression: Avoid empty expression

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#169]
After the recent commit https://github.com/crystal-ameba/ameba/commit/44290a6a5d25c1ece1eab12657ec29cfa0bace87 I pulled in the master branch to test, and now I get 4 failures for `Lint/EmptyExpression` from in my comments:

```
src/avram/callbacks.cr:183:42
[W] Lint/EmptyExpression: Avoid empty expression d t
> # > back the record may not be persisted to the database.
                                         ^
src/avram/callbacks.cr:218:29
[W] Lint/EmptyExpression: Avoid empty expression t b
> # > back the record may not be persisted to the database.
                            ^
src/avram/callbacks.cr:218:51
[W] Lint/EmptyExpression: Avoid empty expression dat
> # > back the record may not be persisted to the database.
                                                  ^
src/avram/callbacks.cr:219:18
[W] Lint/EmptyExpression: Avoid empty expression  `a
> # > Instead use `after_commit`
                 ^
Finished in 936.4 milliseconds
```

You'll see that first one says line 183. Here's a screenshot of that block
<img width="974" alt="Screen Shot 2020-10-23 at 8 55 06 AM" src="https://user-images.githubusercontent.com/2391/97025893-87152480-150d-11eb-85fa-62598d39b336.png">

And the other ones on 218 and 219 are essentially the same comments.
<img width="945" alt="Screen Shot 2020-10-23 at 8 56 46 AM" src="https://user-images.githubusercontent.com/2391/97026024-b4fa6900-150d-11eb-957a-c642c56fae6a.png">

**Comment by veelenga** [comment]
Wow, looking! Sorry about that 😕

**Comment by jwoertink** [comment]
no worries! Thanks for looking in to it ❤️

**Comment by veelenga** [comment]
```
src/avram/callbacks.cr:183:42
src/avram/callbacks.cr:183:44
src/avram/callbacks.cr:218:29
src/avram/callbacks.cr:218:31
src/avram/callbacks.cr:218:51
src/avram/callbacks.cr:218:53
src/avram/callbacks.cr:219:18
src/avram/callbacks.cr:219:20
```
https://github.com/luckyframework/avram/blob/fe7e79d5cc0673215303f50e1fb97627584b7f79/src/avram/callbacks.cr#L183

https://github.com/luckyframework/avram/blob/fe7e79d5cc0673215303f50e1fb97627584b7f79/src/avram/callbacks.cr#L184

https://github.com/luckyframework/avram/blob/fe7e79d5cc0673215303f50e1fb97627584b7f79/src/avram/callbacks.cr#L218

https://github.com/luckyframework/avram/blob/fe7e79d5cc0673215303f50e1fb97627584b7f79/src/avram/callbacks.cr#L219

This is what crystal's compiler points for `NilLiteral`. There is definitely a bug in the compiler I am going to report. For now, I will disable this particular rule `Lint/EmptyExpression` since it highly depends on the location of the AST node.

**Comment by jwoertink** [comment]
@veelenga do we still need to open an issue on crystal?

**Comment by veelenga** [comment]
@jwoertink yeap, I will do in a bit.

**Comment by jwoertink** [comment]
Cool. Nope, I'm good on my end 😄  thanks!
