### ISSUE TITLE
NamedTuple doesn't have compact_map

### ISSUE THREAD

**Issue by stakach** [crystal-ameba/ameba#240]
```
[C] Performance/CompactAfterMap: Use `compact_map {...}` instead of `map {...}.compact`
> opts_string = opts.map { |key, value| "#{key}=#{value}" unless value.nil? }.compact.join("&")
```

However this isn't valid crystal code

```
 388 | opts_string = opts.compact_map { |key, value| "#{key}=#{value}" unless value.nil? }.join("&")
                          ^----------
Error: undefined method 'compact_map' for NamedTuple()
```

**Comment by Sija** [comment]
Since Ameba is doing only a static code analysis, we can't check whether the object in question implements `Enumerable` (see #12).

Since such cases are pretty rare - as seen by the absence of reports for a long time, before you've posted the first one - I'd advise to simply use `# ameba:ignore` pragma and move on.

**Comment by veelenga** [comment]
Unfortunately, this is correct. Performance rules can give some false positives and probably will be moved to an extension someday in the future.

**Comment by stakach** [comment]
makes sense, I like the performance rules - this is probably something that could / should be rectified in the std lib
