### ISSUE TITLE
[Feature Request] Produce a warning for unused methods

### ISSUE THREAD

**Issue by caspiano** [crystal-ameba/ameba#243]
Crystal's behaviour of not type-checking unused code paths can lead to some annoying situations.
A lint that checks that every method is called will help reduce dead and broken code in a codebase.

**Comment by veelenga** [comment]
This can be applied only to unused private methods. This is a part of the roadmap

**Comment by caspiano** [comment]
I think traversing the shard/app's specs may still be useful for producing a warning if a public method that is exported by the project isn't used (can't be guaranteed that it compiles)

**Comment by veelenga** [comment]
What if the shard is some kind of api and public method is designed to be used in a separate dependent shard?

**Comment by caspiano** [comment]
In that case, wouldn't you expect that method to have been spec'd?
I think it could encourage coverage of the library's public surface.

Would it make sense for it to be optional for unused public methods, with private unused method warnings enabled by default?

**Comment by veelenga** [comment]
Ok, i see the point now, thanks. Keep in mind, Ameba makes static analysis only and knows nothing about types, so it is quite hard to do this properly. For example:

```crystal
class MyClass
  def select
    # ...
  end
end

# somewhere in spec...

obj.select { ... } # is this a custom method or the built-in one `Array#select` ?
```

While detecting unused private methods could be a bit easier, since you can use them only in class, finding unused public methods could be challenging and in my understanding doesn't worth it if we disable that by default.

**Comment by Sija** [comment]
Right now it's impossible to do due to the nature of Ameba, so I'm gonna go ahead and close it, at least until some viable solution is found.
