### ISSUE TITLE
Outdated docker hub image

### ISSUE THREAD

**Issue by hugopl** [crystal-ameba/ameba#367]
There's a ameba docker image at https://hub.docker.com/r/veelenga/ameba, however it's way outdated...

For people that can't use Github actions (e.g. companies not hosting their projects under github) a docker image would help a lot to integrate ameba into CI/CD without need to compile it every time.

**Comment by veelenga** [comment]
@hugopl thanks for raising this question. Dockerhub moved the "automated builds" feature from a free to paid plan, and since then we dropped support of ameba images on Dockerhub. 

I can probably start pushing images manually upon release, but not sure if that would be actively used. This is the first request in the last two years for the image on DH.

**Comment by Sija** [comment]
@hugopl Why using the image from ghcr.io is not an option?

**Comment by hugopl** [comment]
I can use it, but the image is outdated (or I checked the wrong place)... and I think that if the update isn't automatic it could/will become outdated again in the future.

**Comment by Sija** [comment]
@hugopl You might be looking in the wrong place, since the image is automatically updated on every push to the `master` branch and release, see https://github.com/crystal-ameba/ameba/pkgs/container/ameba/78109667?tag=latest

**Comment by hugopl** [comment]
I really was, thanks very much!!
