### ISSUE TITLE
Support Windows postinstall

### ISSUE THREAD

**Issue by devnote-dev** [crystal-ameba/ameba#368]
This is a partial resurrection of #230 with a proposal for handling installs on Windows. I believe that until https://github.com/crystal-lang/shards/issues/468 is finally resolved, Ameba's `postinstall` hook should run a Crystal file instead of a Makefile directly, which could then invoke a cmd version of the Makefile for Windows. Something like this:

```crystal
{% if flag?(:win32) %}
  `.\make.cmd build`
{% else %}
  `make bin && make run_file`
{% end %}
```

At least in this way, people attempting to use Ameba on Windows will actually be able to install it instead of getting a confusing error message and having to run the build commands manually.

**Comment by straight-shoota** [comment]
This would be making things *worse* on all other platforms. Instead of running make to build a Crystal program, it would now build a Crystal program to run make to build a Crystal program. That seems pretty crazy to me.

Instead, I'd suggest to avoid building on postinstall. Ameba shouldn't build itself every time it is installed as a dependency. That's annoying and unnecessary and avoidable (cf. https://forum.crystal-lang.org/t/shards-postinstall-considered-harmful/3910 where this project serves as an explicit example).

A better solution is to use a script that builds ameba on demand the first time it's used. This script can be installed automatically (via `executables` key in `shard.yml`) and involve platform-specific variants.
