### ISSUE TITLE
[Feature Request] Language Server Protocol

### ISSUE THREAD

**Issue by keplersj** [crystal-ameba/ameba#37]
For easier editor integration the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) can be used for lint tools like this. 

See:
[VSCode's TSLint LSP Server](https://github.com/Microsoft/vscode-tslint/tree/master/tslint-server)
[VSCode's ESLint LSP Server](https://github.com/Microsoft/vscode-eslint/tree/master/server)

For [Scry](https://github.com/crystal-lang-tools/scry) we have a Crystal implementation of the protocol, and I believe that this would be a very good reason to modularize it as a `lsp` shard.

/cc @faustinoaq

**Comment by veelenga** [comment]
I believe that the tools like Scry (which already implements LSP) can just use ameba. It already uses `Crystal.format` and `crystal build` tools, for example. I don't think ameba should have its own implementation of lsp.

And it seems to be a question of a data format. Ameba uses `Formatter`s for a different kind of output formatting. For example, [this emacs plugin](https://github.com/veelenga/ameba.el) depends on [FlycheckFormatter](https://github.com/veelenga/ameba/blob/c6d842c01d1530ba6f4f528bb2744e9650c4777d/src/ameba/formatter/flycheck_formatter.cr#L2).

So we can add a new formatter suitable for the needs of scry or other LSP implementations.

**Comment by veelenga** [comment]
Here is an example of how this works in ruby together with Rubocop:

https://github.com/mtsmfm/language_server-ruby/blob/2349981fbd625038bd55333d39caa3646dcad987/lib/language_server/linter/rubocop.rb

**Comment by nobodywasishere** [comment]
Zed has separate language servers for rubocop and solargraph / ruby-lsp (https://zed.dev/docs/languages/ruby), it may be worth exploring the creation of a dedicated language server for ameba for this and other editors. I'm fully willing to write / maintain it, especially since I essentially already have this implemented as part of larimar.

I have a prototype setup currently with a custom version of the Zed extension, and a binary available in the larimar repo (all I needed to do was create a separate entrypoint with just the ameba integration), ignore the double reporting:

![Image](https://github.com/user-attachments/assets/de069a65-65ed-43c3-811a-8e33b0442cbc)

**Comment by nobodywasishere** [comment]
The source code for `ameba-ls` is now available here: https://github.com/crystal-lang-tools/ameba-ls

I plan on doing an initial release soon after some more testing is done.
