### ISSUE TITLE
New rule: Unnecessary Method 

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-ameba/ameba#97]
Given the following code:

```crystal
abstract class Parent
  def initialize(@name : String); end
end

class Child < Parent
  def initialize(name : String)
    super
   end
end
```

The child's initializer isn't required since it is the same as the parent.

**Comment by veelenga** [comment]
To be more general, we can report any method which implements only call to `super`, correct?

**Comment by Blacksmoke16** [comment]
Probably as long as the params/types are the same.  For example:
```crystal
abstract class Parent
  def initialize(@name : String); end
end

class Child < Parent
  def initialize(name : String, @value : Int32)
    super name
   end
end
```
Would be required since the parent doesn't have `@value` on it, and is only passing the `name` param.

**Comment by veelenga** [comment]
I found this tricky way to expose parent's private method in std lib:

```crystal
class A
  private def method(a)
    puts a
  end
end

class B < A
  def method(b)
    super
  end
end

B.new.method(10) #=> 10
```

maybe this is not the best architecture but it looks like the language intentionally allows it. So we don't want to disallow this by Ameba. 

FYI Ameba is a syntax analyzer, meaning it can't get info about parent class (it can be located in a different file). So there is no way to distinguish between a real "unnecessary method" and the intentional call to `super`
